# Global settings
workspace_dir = "./workspace"
log_dir = "./logs"
debug = false

# LLM configuration
[llm]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = "sk-..." # Replace with your actual API key
max_tokens = 4096
temperature = 0.0

# Optional configuration for vision model
[llm.vision]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = "sk-..." # Replace with your actual API key

# Browser configuration
[browser]
browser_type = "chromium"
headless = true
disable_security = true
max_content_length = 10000

# Optional proxy configuration
[browser.proxy]
server = "" # e.g., "http://proxy.example.com:8080"
username = ""
password = ""

# Sandbox configuration
[sandbox]
memory_limit = "256m"
cpu_limit = 0.5
disk_limit = "1g"
network_enabled = false
workspace_dir = "/workspace"
timeout = 30
image = "python:3.9-slim"

# Async configuration
worker_count = 2